# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gebruikers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GebruikersID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReviewID', models.IntegerField(max_length=10)),
                ('ReviewTekst', models.CharField(max_length=500)),
                ('ReviewTitel', models.CharField(max_length=50)),
                ('ReviewRating', models.IntegerField(max_length=5)),
                ('Datum', models.DateTimeField(verbose_name='date published')),
                ('Goedgekeurd', models.NullBooleanField()),
                ('GebruikersID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beheerder.Gebruikers')),
            ],
        ),
    ]
